### ISSUE TITLE
"removeViteModuleLoader = true" doesn't work

### ISSUE THREAD

**Issue by humbleCoder1990** [richardtallent/vite-plugin-singlefile#57]
![image](https://user-images.githubusercontent.com/87828192/193129521-a5056c3e-e8d2-4408-8e3b-6ab0378dd4b9.png)
I still see this kind of codes I didn't write in index.html after build.
It seems it came from vite.
The "removeViteModuleLoader = true" option doesn't remove this code..

**Comment by richardtallent** [comment]
The goal of this plugin is to bundle all files together, to the greatest extent possible. The use cases for this plugin are very, very limited -- mostly embedded or non-networked environments.

Splicing JavaScript using RegEx just isn't a good idea, so I'm not going to continue trying to remove all vestigial remnants of Vite or Rollup's own module-loading code, unless that code is actually breaking anything. If the existing option just isn't working anymore due to changes in the loader code, I'll end up just removing the option.

**Comment by Greenheart** [comment]
@humbleCoder1990 Thanks for reporting!

This was a quick fix - PR coming soon.

To fix it, I copied the Vite module loader code into https://regexr.com and copied the broken regex, tweaking it until it worked again.

Vite is maturing and it seems like their module loading strategy hasn't changed too much in the past 12 months. Mostly minor tweaks at this point.

<img width="1566" alt="image" src="https://user-images.githubusercontent.com/6125097/193342996-11c0b4a0-73ea-4236-beb4-7a1b82695be0.png">

I'd really prefer to keep the `removeViteModuleLoader` option in the core library, since it keeps the output as clean as possible. I know that several people in my network are using this option. Also, if we remove it, that means more than 10 of my projects would need to maintain the same regex in their separate build scripts - or use a forked version of `vite-plugin-singlefile` which would keep the option even if it's removed from this version.

A more long term strategy might be to get Vite to not add the module loader script in the first place. Perhaps if we could move the execution of `vite-plugin-singlefile` to another phase of the build process could help with that, since that might allow us to remove the virtual modules that Vite thinks it needs to load with the preloading script. Thus perhaps removing the need for a regex.

**Comment by richardtallent** [comment]
Resolved in the latest release. I adjusted the regex to simplify the logic a bit (and improve performance), hopefully that keeps it rolling for longer this time.

**Comment by Greenheart** [comment]
Nice! Thanks for the consideration!

**Comment by humbleCoder1990** [comment]
I still see same result I posted after upgrading this plugin today.
![image](https://user-images.githubusercontent.com/87828192/194713741-e1fccbc9-d531-464d-a560-977f79dfefae.png)

I enabled the option in vite.config.ts
![image](https://user-images.githubusercontent.com/87828192/194713762-fda559ae-3630-4f58-8ff1-2059ad5a8d78.png)

I'm working app for local enviorment,
So I really need in the use case of removeViteModuleLoader...
But it seems it never works. How can I use it?

**Comment by Greenheart** [comment]
@humbleCoder1990 Hi again! Two things:

1. Are you sure you upgraded to the latest version of `vite-plugin-singlefile` and `vite`?

With the following dependencies, this issue has been resolved for me:
```
vite-plugin-singlefile@0.12.2
vite@3.1.6
```

I've tested in multiple projects with these two versions and `vite-plugin-singlefile@0.12.2` consistently fixes this problem, while `0.12.1` is broken. Thus I'm pretty confident you've not upgraded to the latest version.

However, there is a small chance that something else might be happening, and if so, please follow the instructions below.

---

2. If it's still broken when you have the versions specified above, please create a minimal reproduction repo so we can debug and fix this. Without it, it will be hard to know what's causing it and we won't be able to help you.

To create a minimal reproduction repo, publish a copy of your project as a public GitHub repository, and only keep the code and config that are needed to reproduce the issue.

**Comment by humbleCoder1990** [comment]
@Greenheart 

I'm using vite@3.1.7 & vite-plugin-singlefile@0.12.2.
I think the problem comes when using "vite-tsconfig-paths" plugin.
Could you try to use this plugin together?
https://www.npmjs.com/package/vite-tsconfig-paths

![image](https://user-images.githubusercontent.com/87828192/194980572-fa0357eb-506c-4904-98be-e3a42e4fdeff.png)

**Comment by Greenheart** [comment]
Thanks for the details.

Yes, looking at the code for `vite-tsconfig-paths`, it seems like it could be interfering with `vite-plugin-singlefile`:  https://github.com/aleclarson/vite-tsconfig-paths/blob/master/src/index.ts#L20-L49

@humbleCoder1990 Does your project output a single HTML file after running both plugins? Or does it fail completely and output a regular build bundle?

Can you provide a minimal reproduction repository? Make a copy of your project where you get this issue, and remove all sensitive details plus irrelevant code and config. Then publish this as a public GitHub repository that we can use to debug this.

Without a reproduction, this will be hard to fix.

**Comment by bddjr** [comment]
## This is completely unnecessary work, and polyfill should be turned off directly in `vite.config.ts`
https://vite.dev/config/build-options.html#build-modulepreload
```ts
build: {
	modulePreload: {
		polyfill: false,
	},
},
```

**Comment by bddjr** [comment]
The code is too messy, I don't know if I should submit a Pull Request. 
I've already had problems installing dependencies on Windows.
```
PS D:\bddjr\Desktop\code\frontend\vite-plugin-singlefile> npm i

> vite-plugin-singlefile@2.0.2 prepare
> npm run build


> vite-plugin-singlefile@2.0.2 build
> rimraf dist && tsc -p tsconfig.json && tsc -p tsconfig-cjs.json && ./fixup

'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm error code 1
npm error path D:\bddjr\Desktop\code\frontend\vite-plugin-singlefile
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c npm run build
npm error A complete log of this run can be found in: C:\Users\bddjr\AppData\Local\npm-cache\_logs\2024-10-03T05_34_46_612Z-debug-0.log
```

**Comment by Greenheart** [comment]
> polyfill should be turned off directly in `vite.config.ts`

Thanks @bddjr! That config looks promising, and should be investigated.

**Comment by bddjr** [comment]
I aim to create a superior version to address several issues that I am aware of.  
Because more code has been changed, the PR may be rejected.
